// Code generated by goyacc -o sql.go -p sql -v sql.output sql.y. DO NOT EDIT.

//line sql.y:2

package parser

import __yyfmt__ "fmt"

//line sql.y:3

import (
	"github.com/deepfabric/thinkbase/pkg/sql/tree"
	"github.com/deepfabric/thinkbase/pkg/vm/value"
)

//line sql.y:13

type sqlSymUnion struct {
	val interface{}
}

func (u *sqlSymUnion) bool() bool {
	return u.val.(bool)
}

func (u *sqlSymUnion) isNull() bool {
	return u.val == nil
}

func (u *sqlSymUnion) setNegative() *tree.Value {
	v, ok := u.val.(*tree.Value)
	if !ok {
		return nil
	}
	i, ok := value.AsInt(v.E)
	if !ok {
		return nil
	}
	return &tree.Value{value.NewInt(int64(i) * -1)}
}

func (u *sqlSymUnion) valueStatement() *tree.Value {
	return u.val.(*tree.Value)
}

func (u *sqlSymUnion) selectStatement() *tree.Select {
	return u.val.(*tree.Select)
}

func (u *sqlSymUnion) limitStatement() *tree.Limit {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.Limit)
}

func (u *sqlSymUnion) orderByStatement() tree.OrderBy {
	if u.val == nil {
		return nil
	}
	return u.val.(tree.OrderBy)
}

func (u *sqlSymUnion) relationStatement() tree.RelationStatement {
	if u.val == nil {
		return nil
	}
	return u.val.(tree.RelationStatement)
}

func (u *sqlSymUnion) joinStatement() *tree.JoinClause {
	return u.val.(*tree.JoinClause)
}

func (u *sqlSymUnion) unionStatement() *tree.UnionClause {
	return u.val.(*tree.UnionClause)
}

func (u *sqlSymUnion) simpleSelectStatement() *tree.SelectClause {
	return u.val.(*tree.SelectClause)
}

func (u *sqlSymUnion) fromStatement() *tree.From {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.From)
}

func (u *sqlSymUnion) groupByStatement() *tree.GroupBy {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.GroupBy)
}

func (u *sqlSymUnion) whereStatement() *tree.Where {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.Where)
}

func (u *sqlSymUnion) subqueryStatement() *tree.Subquery {
	return u.val.(*tree.Subquery)
}

func (u *sqlSymUnion) funcStatement() *tree.FuncExpr {
	return u.val.(*tree.FuncExpr)
}

func (u *sqlSymUnion) selectExprs() tree.SelectExprs {
	return u.val.(tree.SelectExprs)
}

func (u *sqlSymUnion) selectExpr() *tree.SelectExpr {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.SelectExpr)
}

func (u *sqlSymUnion) tableStatements() tree.TableStatements {
	return u.val.(tree.TableStatements)
}

func (u *sqlSymUnion) tableStatement() tree.TableStatement {
	return u.val.(tree.TableStatement)
}

func (u *sqlSymUnion) limit() *tree.Limit {
	return u.val.(*tree.Limit)
}

func (u *sqlSymUnion) orderStatement() *tree.Order {
	return u.val.(*tree.Order)
}

func (u *sqlSymUnion) direction() tree.Direction {
	return u.val.(tree.Direction)
}

func (u *sqlSymUnion) joinType() tree.JoinType {
	return u.val.(tree.JoinType)
}

func (u *sqlSymUnion) joinCond() tree.JoinCond {
	return u.val.(tree.JoinCond)
}

func (u *sqlSymUnion) tableName() *tree.TableName {
	return u.val.(*tree.TableName)
}

func (u *sqlSymUnion) nameList() tree.NameList {
	return u.val.(tree.NameList)
}

func (u *sqlSymUnion) exprStatement() tree.ExprStatement {
	return u.val.(tree.ExprStatement)
}

func (u *sqlSymUnion) exprStatements() tree.ExprStatements {
	return u.val.(tree.ExprStatements)
}

func (u *sqlSymUnion) colunmNameList() tree.ColunmNameList {
	return u.val.(tree.ColunmNameList)
}

func (u *sqlSymUnion) aliasClause() *tree.AliasClause {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.AliasClause)
}

//line sql.y:226
type sqlSymType struct {
	yys   int
	id    int32
	pos   int32
	byt   byte
	str   string
	union sqlSymUnion
}

const IDENT = 57346
const ICONST = 57347
const FCONST = 57348
const SCONST = 57349
const LESS_EQUALS = 57350
const GREATER_EQUALS = 57351
const NOT_EQUALS = 57352
const ALL = 57353
const AND = 57354
const AS = 57355
const ASC = 57356
const BETWEEN = 57357
const BOOL = 57358
const BY = 57359
const CAST = 57360
const CROSS = 57361
const DESC = 57362
const DISTINCT = 57363
const EXCEPT = 57364
const EXISTS = 57365
const FALSE = 57366
const FETCH = 57367
const FIRST = 57368
const FLOAT = 57369
const FROM = 57370
const FULL = 57371
const GROUP = 57372
const HAVING = 57373
const INNER = 57374
const INT = 57375
const INTERSECT = 57376
const IS = 57377
const JOIN = 57378
const NATURAL = 57379
const NEXT = 57380
const NOT = 57381
const NULL = 57382
const OFFSET = 57383
const ON = 57384
const ONLY = 57385
const OR = 57386
const ORDER = 57387
const OUTER = 57388
const RIGHT = 57389
const ROW = 57390
const ROWS = 57391
const SELECT = 57392
const STRING = 57393
const TIME = 57394
const TRUE = 57395
const UNION = 57396
const WHERE = 57397
const NOT_LA = 57398
const AT = 57399
const UMINUS = 57400
const LEFT = 57401

var sqlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"ICONST",
	"FCONST",
	"SCONST",
	"LESS_EQUALS",
	"GREATER_EQUALS",
	"NOT_EQUALS",
	"ALL",
	"AND",
	"AS",
	"ASC",
	"BETWEEN",
	"BOOL",
	"BY",
	"CAST",
	"CROSS",
	"DESC",
	"DISTINCT",
	"EXCEPT",
	"EXISTS",
	"FALSE",
	"FETCH",
	"FIRST",
	"FLOAT",
	"FROM",
	"FULL",
	"GROUP",
	"HAVING",
	"INNER",
	"INT",
	"INTERSECT",
	"IS",
	"JOIN",
	"NATURAL",
	"NEXT",
	"NOT",
	"NULL",
	"OFFSET",
	"ON",
	"ONLY",
	"OR",
	"ORDER",
	"OUTER",
	"RIGHT",
	"ROW",
	"ROWS",
	"SELECT",
	"STRING",
	"TIME",
	"TRUE",
	"UNION",
	"WHERE",
	"NOT_LA",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'<'",
	"'>'",
	"'='",
	"'['",
	"']'",
	"'('",
	"')'",
	"'.'",
	"AT",
	"UMINUS",
	"LEFT",
	"','",
}
var sqlStatenames = [...]string{}

const sqlEofCode = 1
const sqlErrCode = 2
const sqlInitialStackSize = 16

//line sql.y:774

//line yacctab:1
var sqlExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 4,
	1, 5,
	25, 5,
	41, 5,
	68, 5,
	-2, 108,
	-1, 53,
	67, 139,
	-2, 130,
}

const sqlPrivate = 57344

const sqlLast = 408

var sqlAct = [...]int{

	53, 10, 38, 211, 167, 188, 5, 184, 121, 41,
	10, 141, 176, 123, 133, 136, 126, 229, 201, 66,
	83, 85, 230, 200, 34, 10, 81, 32, 200, 191,
	179, 106, 18, 236, 164, 90, 65, 185, 112, 111,
	52, 22, 198, 110, 21, 138, 107, 108, 78, 105,
	11, 26, 60, 10, 29, 16, 20, 227, 24, 25,
	88, 40, 91, 195, 134, 82, 127, 173, 10, 28,
	62, 10, 10, 10, 10, 74, 19, 10, 13, 94,
	95, 96, 63, 89, 10, 61, 63, 90, 118, 122,
	142, 76, 87, 143, 27, 150, 151, 152, 153, 154,
	155, 156, 157, 158, 159, 160, 161, 163, 145, 13,
	139, 144, 146, 147, 114, 73, 228, 72, 128, 174,
	175, 129, 130, 131, 132, 119, 127, 135, 116, 172,
	89, 13, 46, 47, 48, 165, 168, 169, 177, 178,
	117, 52, 183, 127, 127, 57, 113, 186, 149, 148,
	39, 50, 75, 4, 212, 12, 192, 193, 88, 187,
	194, 22, 4, 190, 21, 197, 37, 51, 189, 62,
	88, 26, 9, 213, 29, 162, 20, 3, 24, 25,
	49, 89, 64, 203, 43, 44, 210, 17, 207, 28,
	87, 208, 10, 89, 52, 166, 19, 204, 142, 216,
	215, 143, 87, 214, 122, 4, 88, 13, 46, 47,
	48, 206, 235, 30, 27, 205, 13, 88, 232, 233,
	234, 57, 45, 218, 33, 219, 39, 50, 55, 89,
	109, 237, 13, 46, 47, 48, 67, 231, 168, 13,
	89, 54, 37, 51, 68, 84, 57, 171, 125, 87,
	220, 39, 50, 221, 69, 124, 49, 70, 71, 36,
	43, 44, 35, 13, 46, 47, 48, 37, 51, 137,
	52, 199, 92, 93, 94, 95, 96, 57, 115, 22,
	170, 49, 39, 50, 23, 43, 44, 35, 58, 26,
	59, 22, 29, 140, 20, 52, 24, 25, 37, 51,
	217, 26, 13, 209, 29, 196, 120, 28, 24, 25,
	88, 86, 49, 14, 15, 31, 43, 44, 42, 28,
	13, 46, 47, 48, 223, 56, 52, 180, 8, 77,
	7, 6, 27, 89, 57, 225, 100, 101, 102, 2,
	50, 222, 87, 103, 27, 92, 93, 94, 95, 96,
	92, 93, 94, 95, 96, 1, 51, 79, 80, 226,
	224, 0, 0, 0, 0, 0, 0, 0, 0, 49,
	88, 0, 181, 43, 44, 88, 202, 0, 182, 0,
	0, 0, 0, 52, 104, 92, 93, 94, 95, 96,
	97, 98, 99, 89, 0, 0, 0, 0, 89, 0,
	0, 0, 87, 0, 0, 0, 0, 87,
}
var sqlPact = [...]int{

	105, -1000, -1000, -1000, 10, -1000, -1000, -1000, -1000, 105,
	-37, 142, 203, -1000, 45, -1000, 165, -32, 212, 233,
	233, 233, 81, 79, 105, 55, 2, 2, 2, -1000,
	-8, 228, -1000, -1000, 298, -1000, -1000, 259, 328, -27,
	-1000, -1000, -38, 316, 316, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 105, -22, -1000, -1000, -28, -29, -1000, -1000,
	41, 144, 102, 259, 259, 235, -1000, 105, -1000, -1000,
	105, 105, 105, 105, 22, -1000, 105, -1000, -1000, -1000,
	-1000, -10, 228, 74, -8, -1000, 212, 259, 259, 109,
	-1000, 95, 316, 316, 316, 316, 316, 316, 316, 316,
	316, 316, 316, 316, 160, -1000, 212, 20, 20, -34,
	259, 127, 259, -1000, -1000, 62, -1000, -1000, 158, 90,
	-43, -1000, 358, -1000, -1000, 212, -30, -1000, 260, 272,
	260, -1000, 22, -1000, 259, -1000, 138, -1000, 259, -1000,
	-44, -1000, 235, 235, -10, -1000, 194, 95, -1000, 23,
	20, 20, -1000, -1000, -1000, 215, 215, 215, 215, 215,
	215, 293, 316, -23, -1000, 205, -1000, -50, 158, 363,
	90, -1000, 259, -1000, 210, 206, -1000, -1000, -1000, 259,
	-1000, -1000, -1000, -30, -1000, 212, -1000, 158, 123, 156,
	158, 74, -1000, -1000, 138, -1000, 316, 288, 259, -1000,
	259, -1000, 308, 14, 48, -1000, -1000, -1000, -1000, -51,
	-1000, -1000, 259, 259, -1000, 123, 215, 316, 146, 158,
	-35, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	212, 158, -45, -1000, 215, -1000, -1000, -1000,
}
var sqlPgo = [...]int{

	0, 355, 339, 177, 152, 331, 330, 50, 328, 9,
	327, 0, 325, 16, 21, 6, 318, 315, 7, 314,
	313, 306, 303, 26, 293, 4, 213, 5, 290, 288,
	236, 329, 14, 284, 52, 85, 280, 12, 278, 269,
	15, 24, 2, 259, 61, 3, 255, 13, 8, 11,
	27, 253, 250, 247, 241, 228, 222,
}
var sqlR1 = [...]int{

	0, 1, 2, 3, 20, 20, 19, 21, 21, 48,
	10, 10, 10, 29, 29, 28, 28, 28, 28, 34,
	35, 35, 36, 36, 36, 37, 37, 38, 38, 4,
	4, 4, 4, 4, 8, 8, 17, 26, 26, 50,
	50, 50, 50, 23, 23, 24, 24, 40, 40, 39,
	27, 27, 45, 45, 25, 25, 41, 41, 41, 41,
	41, 41, 41, 42, 42, 42, 42, 42, 42, 42,
	42, 42, 42, 42, 43, 43, 43, 43, 43, 43,
	43, 43, 43, 44, 44, 44, 44, 44, 44, 53,
	53, 53, 56, 56, 54, 54, 55, 52, 51, 51,
	51, 51, 51, 46, 46, 47, 47, 9, 7, 6,
	6, 6, 30, 30, 30, 5, 5, 5, 5, 32,
	33, 33, 33, 33, 31, 31, 49, 49, 15, 15,
	16, 16, 16, 16, 18, 18, 22, 22, 11, 12,
	14, 13,
}
var sqlR2 = [...]int{

	0, 1, 1, 3, 1, 0, 3, 1, 3, 2,
	1, 1, 0, 1, 0, 2, 2, 1, 1, 5,
	2, 3, 1, 3, 0, 1, 1, 1, 1, 1,
	1, 1, 1, 4, 6, 7, 1, 1, 3, 1,
	2, 3, 1, 2, 0, 1, 3, 1, 0, 2,
	3, 0, 2, 0, 1, 3, 1, 2, 3, 3,
	3, 4, 1, 1, 1, 1, 2, 2, 3, 3,
	3, 3, 3, 1, 3, 3, 3, 3, 3, 3,
	5, 6, 2, 1, 1, 1, 1, 1, 1, 1,
	2, 2, 1, 1, 3, 4, 6, 1, 1, 1,
	1, 1, 1, 3, 2, 1, 0, 3, 1, 4,
	4, 4, 1, 1, 0, 4, 5, 4, 4, 2,
	2, 2, 2, 1, 1, 0, 2, 2, 1, 3,
	1, 4, 3, 6, 3, 0, 1, 3, 1, 1,
	1, 1,
}
var sqlChk = [...]int{

	-1000, -1, -2, -3, -4, -15, -5, -6, -8, 67,
	-11, -7, 50, 4, -20, -19, 45, -3, 69, 54,
	34, 22, 19, -33, 36, 37, 29, 72, 47, 32,
	-26, -17, -50, 21, -41, 59, -43, 39, -42, 23,
	-44, -9, -16, 57, 58, -56, 5, 6, 7, 53,
	24, 40, 67, -11, -54, -55, -12, 18, -29, -28,
	-34, -35, 25, 41, 17, 68, -11, -30, 11, 21,
	-30, -30, 36, 36, -7, -4, 36, -31, 46, -31,
	-31, -23, 73, 28, -26, -14, 13, 44, 12, 35,
	-11, -41, 57, 58, 59, 60, 61, 62, 63, 64,
	8, 9, 10, 15, 56, -9, 69, -42, -42, -3,
	65, 67, 67, -35, -34, -38, 26, 38, -41, -44,
	-21, -48, -41, -47, -46, 13, -13, -11, -7, -7,
	-7, -7, -7, -32, 42, -7, -40, -39, 55, -50,
	-24, -49, -15, -9, -23, -14, -41, -41, 40, 39,
	-42, -42, -42, -42, -42, -42, -42, -42, -42, -42,
	-42, -42, 15, -11, 68, -41, 68, -25, -41, -41,
	-36, -53, 67, 5, 57, 58, -37, 48, 49, 73,
	-10, 14, 20, -13, -18, 67, -32, -41, -27, 30,
	-41, 73, -47, -47, -40, 40, 12, -42, 65, 66,
	73, 68, 13, -37, -41, 5, 5, -48, -18, -22,
	-11, -45, 31, 17, -49, -27, -42, 12, -41, -41,
	-52, -51, 33, 16, 52, 27, 51, 43, 68, 68,
	73, -41, -25, -45, -42, 66, 68, -11,
}
var sqlDef = [...]int{

	0, -2, 1, 2, -2, 29, 30, 31, 32, 0,
	128, 0, 0, 138, 14, 4, 0, 0, 0, 114,
	114, 114, 0, 0, 0, 0, 125, 125, 125, 123,
	44, 0, 37, 36, 39, 42, 56, 0, 62, 0,
	63, 64, 65, 0, 0, 73, 83, 84, 85, 86,
	87, 88, 0, -2, 92, 93, 0, 0, 3, 13,
	17, 18, 0, 0, 0, 106, 129, 0, 112, 113,
	0, 0, 0, 0, 0, 108, 0, 120, 124, 121,
	122, 48, 0, 0, 44, 40, 0, 0, 0, 0,
	140, 57, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 82, 0, 66, 67, 0,
	0, 0, 0, 15, 16, 24, 27, 28, 20, 63,
	6, 7, 12, 33, 105, 0, 135, 141, 109, 110,
	111, 115, 0, 117, 0, 118, 51, 47, 0, 38,
	43, 45, 106, 106, 48, 41, 58, 59, 60, 0,
	68, 69, 70, 71, 72, 74, 75, 76, 77, 78,
	79, 0, 0, 132, 107, 0, 94, 0, 54, 0,
	0, 22, 0, 89, 0, 0, 21, 25, 26, 0,
	9, 10, 11, 135, 104, 0, 116, 119, 53, 0,
	49, 0, 126, 127, 51, 61, 0, 0, 0, 131,
	0, 95, 0, 0, 0, 90, 91, 8, 103, 0,
	136, 34, 0, 0, 46, 53, 80, 0, 0, 55,
	0, 97, 98, 99, 100, 101, 102, 19, 23, 134,
	0, 52, 50, 35, 81, 133, 96, 137,
}
var sqlTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 61, 3, 3,
	67, 68, 59, 57, 73, 58, 69, 60, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	62, 64, 63, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 65, 3, 66,
}
var sqlTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 70, 71, 72,
}
var sqlTok3 = [...]int{
	0,
}

var sqlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	sqlDebug        = 0
	sqlErrorVerbose = false
)

type sqlLexer interface {
	Lex(lval *sqlSymType) int
	Error(s string)
}

type sqlParser interface {
	Parse(sqlLexer) int
	Lookahead() int
}

type sqlParserImpl struct {
	lval  sqlSymType
	stack [sqlInitialStackSize]sqlSymType
	char  int
}

func (p *sqlParserImpl) Lookahead() int {
	return p.char
}

func sqlNewParser() sqlParser {
	return &sqlParserImpl{}
}

const sqlFlag = -1000

func sqlTokname(c int) string {
	if c >= 1 && c-1 < len(sqlToknames) {
		if sqlToknames[c-1] != "" {
			return sqlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func sqlStatname(s int) string {
	if s >= 0 && s < len(sqlStatenames) {
		if sqlStatenames[s] != "" {
			return sqlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func sqlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !sqlErrorVerbose {
		return "syntax error"
	}

	for _, e := range sqlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + sqlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := sqlPact[state]
	for tok := TOKSTART; tok-1 < len(sqlToknames); tok++ {
		if n := base + tok; n >= 0 && n < sqlLast && sqlChk[sqlAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if sqlDef[state] == -2 {
		i := 0
		for sqlExca[i] != -1 || sqlExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; sqlExca[i] >= 0; i += 2 {
			tok := sqlExca[i]
			if tok < TOKSTART || sqlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if sqlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += sqlTokname(tok)
	}
	return res
}

func sqllex1(lex sqlLexer, lval *sqlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = sqlTok1[0]
		goto out
	}
	if char < len(sqlTok1) {
		token = sqlTok1[char]
		goto out
	}
	if char >= sqlPrivate {
		if char < sqlPrivate+len(sqlTok2) {
			token = sqlTok2[char-sqlPrivate]
			goto out
		}
	}
	for i := 0; i < len(sqlTok3); i += 2 {
		token = sqlTok3[i+0]
		if token == char {
			token = sqlTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = sqlTok2[1] /* unknown char */
	}
	if sqlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", sqlTokname(token), uint(char))
	}
	return char, token
}

func sqlParse(sqllex sqlLexer) int {
	return sqlNewParser().Parse(sqllex)
}

func (sqlrcvr *sqlParserImpl) Parse(sqllex sqlLexer) int {
	var sqln int
	var sqlVAL sqlSymType
	var sqlDollar []sqlSymType
	_ = sqlDollar // silence set and not used
	sqlS := sqlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	sqlstate := 0
	sqlrcvr.char = -1
	sqltoken := -1 // sqlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		sqlstate = -1
		sqlrcvr.char = -1
		sqltoken = -1
	}()
	sqlp := -1
	goto sqlstack

ret0:
	return 0

ret1:
	return 1

sqlstack:
	/* put a state and value onto the stack */
	if sqlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", sqlTokname(sqltoken), sqlStatname(sqlstate))
	}

	sqlp++
	if sqlp >= len(sqlS) {
		nyys := make([]sqlSymType, len(sqlS)*2)
		copy(nyys, sqlS)
		sqlS = nyys
	}
	sqlS[sqlp] = sqlVAL
	sqlS[sqlp].yys = sqlstate

sqlnewstate:
	sqln = sqlPact[sqlstate]
	if sqln <= sqlFlag {
		goto sqldefault /* simple state */
	}
	if sqlrcvr.char < 0 {
		sqlrcvr.char, sqltoken = sqllex1(sqllex, &sqlrcvr.lval)
	}
	sqln += sqltoken
	if sqln < 0 || sqln >= sqlLast {
		goto sqldefault
	}
	sqln = sqlAct[sqln]
	if sqlChk[sqln] == sqltoken { /* valid shift */
		sqlrcvr.char = -1
		sqltoken = -1
		sqlVAL = sqlrcvr.lval
		sqlstate = sqln
		if Errflag > 0 {
			Errflag--
		}
		goto sqlstack
	}

sqldefault:
	/* default state action */
	sqln = sqlDef[sqlstate]
	if sqln == -2 {
		if sqlrcvr.char < 0 {
			sqlrcvr.char, sqltoken = sqllex1(sqllex, &sqlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if sqlExca[xi+0] == -1 && sqlExca[xi+1] == sqlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			sqln = sqlExca[xi+0]
			if sqln < 0 || sqln == sqltoken {
				break
			}
		}
		sqln = sqlExca[xi+1]
		if sqln < 0 {
			goto ret0
		}
	}
	if sqln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			sqllex.Error(sqlErrorMessage(sqlstate, sqltoken))
			Nerrs++
			if sqlDebug >= 1 {
				__yyfmt__.Printf("%s", sqlStatname(sqlstate))
				__yyfmt__.Printf(" saw %s\n", sqlTokname(sqltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for sqlp >= 0 {
				sqln = sqlPact[sqlS[sqlp].yys] + sqlErrCode
				if sqln >= 0 && sqln < sqlLast {
					sqlstate = sqlAct[sqln] /* simulate a shift of "error" */
					if sqlChk[sqlstate] == sqlErrCode {
						goto sqlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if sqlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", sqlS[sqlp].yys)
				}
				sqlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if sqlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", sqlTokname(sqltoken))
			}
			if sqltoken == sqlEofCode {
				goto ret1
			}
			sqlrcvr.char = -1
			sqltoken = -1
			goto sqlnewstate /* try again in the same state */
		}
	}

	/* reduction by production sqln */
	if sqlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", sqln, sqlStatname(sqlstate))
	}

	sqlnt := sqln
	sqlpt := sqlp
	_ = sqlpt // guard against "declared and not used"

	sqlp -= sqlR2[sqln]
	// sqlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if sqlp+1 >= len(sqlS) {
		nyys := make([]sqlSymType, len(sqlS)*2)
		copy(nyys, sqlS)
		sqlS = nyys
	}
	sqlVAL = sqlS[sqlp+1]

	/* consult goto table to find next state */
	sqln = sqlR1[sqln]
	sqlg := sqlPgo[sqln]
	sqlj := sqlg + sqlS[sqlp].yys + 1

	if sqlj >= sqlLast {
		sqlstate = sqlAct[sqlg]
	} else {
		sqlstate = sqlAct[sqlj]
		if sqlChk[sqlstate] != -sqln {
			sqlstate = sqlAct[sqlg]
		}
	}
	// dummy call; replaced with literal code
	switch sqlnt {

	case 1:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:320
		{
			sqllex.(*lexer).SetStmt(sqlDollar[1].union.selectStatement())
		}
	case 2:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:322
		{
			sqlVAL.union.val = sqlDollar[1].union.selectStatement()
		}
	case 3:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:325
		{
			sqlVAL.union.val = &tree.Select{
				Limit:    sqlDollar[3].union.limitStatement(),
				OrderBy:  sqlDollar[2].union.orderByStatement(),
				Relation: sqlDollar[1].union.relationStatement(),
			}
		}
	case 4:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:335
		{
			sqlVAL.union.val = sqlDollar[1].union.orderByStatement()
		}
	case 5:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:336
		{
			sqlVAL.union.val = nil
		}
	case 6:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:338
		{
			sqlVAL.union.val = sqlDollar[3].union.orderByStatement()
		}
	case 7:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:340
		{
			sqlVAL.union.val = tree.OrderBy{sqlDollar[1].union.orderStatement()}
		}
	case 8:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:341
		{
			sqlVAL.union.val = append(sqlDollar[1].union.orderByStatement(), sqlDollar[3].union.orderStatement())
		}
	case 9:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:344
		{
			sqlVAL.union.val = &tree.Order{
				E:    sqlDollar[1].union.exprStatement(),
				Type: sqlDollar[2].union.direction(),
			}
		}
	case 10:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:351
		{
			sqlVAL.union.val = tree.Ascending
		}
	case 11:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:352
		{
			sqlVAL.union.val = tree.Descending
		}
	case 12:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:353
		{
			sqlVAL.union.val = tree.DefaultDirection
		}
	case 13:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:356
		{
			sqlVAL.union.val = sqlDollar[1].union.limitStatement()
		}
	case 14:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:357
		{
			sqlVAL.union.val = nil
		}
	case 15:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:360
		{
			if sqlDollar[1].union.limitStatement() == nil {
				sqlVAL.union.val = sqlDollar[2].union.limitStatement()
			} else {
				sqlVAL.union.val = sqlDollar[1].union.limitStatement()
				sqlVAL.union.val.(*tree.Limit).Offset = sqlDollar[2].union.limitStatement().Offset
			}
		}
	case 16:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:369
		{
			sqlVAL.union.val = sqlDollar[1].union.limitStatement()
			if sqlDollar[2].union.limitStatement() != nil {
				sqlVAL.union.val.(*tree.Limit).Count = sqlDollar[2].union.limitStatement().Count
			}
		}
	case 17:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:376
		{
			sqlVAL.union.val = sqlDollar[1].union.limitStatement()
		}
	case 18:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:380
		{
			sqlVAL.union.val = sqlDollar[1].union.limitStatement()
		}
	case 19:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:385
		{
			sqlVAL.union.val = &tree.Limit{Count: sqlDollar[3].union.exprStatement()}
		}
	case 20:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:389
		{
			sqlVAL.union.val = &tree.Limit{Offset: sqlDollar[2].union.exprStatement()}
		}
	case 21:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:390
		{
			sqlVAL.union.val = &tree.Limit{Offset: sqlDollar[2].union.exprStatement()}
		}
	case 22:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:392
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 23:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:393
		{
			sqlVAL.union.val = sqlDollar[2].union.exprStatement()
		}
	case 24:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:394
		{
			sqlVAL.union.val = &tree.Value{value.NewInt(1)}
		}
	case 25:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:396
		{
		}
	case 26:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:397
		{
		}
	case 27:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:399
		{
		}
	case 28:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:400
		{
		}
	case 29:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:404
		{
			sqlVAL.union.val = sqlDollar[1].union.tableName()
		}
	case 30:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:405
		{
			sqlVAL.union.val = sqlDollar[1].union.joinStatement()
		}
	case 31:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:406
		{
			sqlVAL.union.val = sqlDollar[1].union.unionStatement()
		}
	case 32:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:407
		{
			sqlVAL.union.val = sqlDollar[1].union.simpleSelectStatement()
		}
	case 33:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:408
		{
			sqlVAL.union.val = &tree.AliasedSelect{
				As:  sqlDollar[4].union.aliasClause(),
				Sel: sqlDollar[2].union.selectStatement(),
			}
		}
	case 34:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:416
		{
			sqlVAL.union.val = &tree.SelectClause{
				Distinct: false,
				Sel:      sqlDollar[2].union.selectExprs(),
				From:     sqlDollar[3].union.fromStatement(),
				Where:    sqlDollar[4].union.whereStatement(),
				Having:   sqlDollar[6].union.whereStatement(),
				GroupBy:  sqlDollar[5].union.groupByStatement(),
			}
		}
	case 35:
		sqlDollar = sqlS[sqlpt-7 : sqlpt+1]
//line sql.y:427
		{
			sqlVAL.union.val = &tree.SelectClause{
				Distinct: sqlDollar[2].union.bool(),
				Sel:      sqlDollar[3].union.selectExprs(),
				From:     sqlDollar[4].union.fromStatement(),
				Where:    sqlDollar[5].union.whereStatement(),
				Having:   sqlDollar[7].union.whereStatement(),
				GroupBy:  sqlDollar[6].union.groupByStatement(),
			}
		}
	case 36:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:440
		{
			sqlVAL.union.val = true
		}
	case 37:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:445
		{
			if sqlDollar[1].union.isNull() {
				sqlVAL.union.val = tree.SelectExprs{}
			} else {
				sqlVAL.union.val = tree.SelectExprs{sqlDollar[1].union.selectExpr()}
			}
		}
	case 38:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:453
		{
			if sqlDollar[3].union.isNull() {
				sqlVAL.union.val = sqlDollar[1].union.selectExprs()
			} else {
				sqlVAL.union.val = append(sqlDollar[1].union.selectExprs(), sqlDollar[3].union.selectExpr())
			}
		}
	case 39:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:462
		{
			sqlVAL.union.val = &tree.SelectExpr{E: sqlDollar[1].union.exprStatement()}
		}
	case 40:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:466
		{
			sqlVAL.union.val = &tree.SelectExpr{E: sqlDollar[1].union.exprStatement(), As: tree.Name(sqlDollar[2].str)}
		}
	case 41:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:470
		{
			sqlVAL.union.val = &tree.SelectExpr{E: sqlDollar[1].union.exprStatement(), As: tree.Name(sqlDollar[3].str)}
		}
	case 42:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:474
		{
			sqlVAL.union.val = nil
		}
	case 43:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:481
		{
			sqlVAL.union.val = &tree.From{sqlDollar[2].union.tableStatements()}
		}
	case 44:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:484
		{
			sqlVAL.union.val = nil
		}
	case 45:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:487
		{
			sqlVAL.union.val = tree.TableStatements{sqlDollar[1].union.tableStatement()}
		}
	case 46:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:491
		{
			sqlVAL.union.val = append(sqlDollar[1].union.tableStatements(), sqlDollar[3].union.tableStatement())
		}
	case 47:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:498
		{
			sqlVAL.union.val = &tree.Where{Type: tree.AstWhere, E: sqlDollar[1].union.exprStatement()}
		}
	case 48:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:501
		{
			sqlVAL.union.val = nil
		}
	case 49:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:503
		{
			sqlVAL.union.val = sqlDollar[2].union.exprStatement()
		}
	case 50:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:507
		{
			sqlVAL.union.val = &tree.GroupBy{sqlDollar[3].union.exprStatements()}
		}
	case 51:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:508
		{
			sqlVAL.union.val = nil
		}
	case 52:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:513
		{
			sqlVAL.union.val = &tree.Where{Type: tree.AstHaving, E: sqlDollar[2].union.exprStatement()}
		}
	case 53:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:516
		{
			sqlVAL.union.val = nil
		}
	case 54:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:520
		{
			sqlVAL.union.val = tree.ExprStatements{sqlDollar[1].union.exprStatement()}
		}
	case 55:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:521
		{
			sqlVAL.union.val = append(sqlDollar[1].union.exprStatements(), sqlDollar[3].union.exprStatement())
		}
	case 56:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:523
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 57:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:524
		{
			sqlVAL.union.val = &tree.NotExpr{E: sqlDollar[2].union.exprStatement()}
		}
	case 58:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:525
		{
			sqlVAL.union.val = &tree.OrExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 59:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:526
		{
			sqlVAL.union.val = &tree.AndExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 60:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:527
		{
			sqlVAL.union.val = &tree.IsNullExpr{E: sqlDollar[1].union.exprStatement()}
		}
	case 61:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:528
		{
			sqlVAL.union.val = &tree.IsNotNullExpr{E: sqlDollar[1].union.exprStatement()}
		}
	case 62:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:529
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 63:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:531
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 64:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:532
		{
			sqlVAL.union.val = sqlDollar[1].union.subqueryStatement()
		}
	case 65:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:533
		{
			sqlVAL.union.val = sqlDollar[1].union.colunmNameList()
		}
	case 66:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:534
		{
			sqlVAL.union.val = sqlDollar[2].union.exprStatement()
		}
	case 67:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:535
		{
			sqlVAL.union.val = &tree.UnaryMinusExpr{E: sqlDollar[2].union.exprStatement()}
		}
	case 68:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:536
		{
			sqlVAL.union.val = &tree.PlusExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 69:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:537
		{
			sqlVAL.union.val = &tree.MinusExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 70:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:538
		{
			sqlVAL.union.val = &tree.MultExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 71:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:539
		{
			sqlVAL.union.val = &tree.DivExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 72:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:540
		{
			sqlVAL.union.val = &tree.ModExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 73:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:541
		{
			sqlVAL.union.val = sqlDollar[1].union.funcStatement()
		}
	case 74:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:543
		{
			sqlVAL.union.val = &tree.LtExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 75:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:544
		{
			sqlVAL.union.val = &tree.GtExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 76:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:545
		{
			sqlVAL.union.val = &tree.EqExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 77:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:546
		{
			sqlVAL.union.val = &tree.LeExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 78:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:547
		{
			sqlVAL.union.val = &tree.GeExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 79:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:548
		{
			sqlVAL.union.val = &tree.NeExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 80:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:549
		{
			sqlVAL.union.val = &tree.BetweenExpr{E: sqlDollar[1].union.exprStatement(), From: sqlDollar[3].union.exprStatement(), To: sqlDollar[5].union.exprStatement()}
		}
	case 81:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:550
		{
			sqlVAL.union.val = &tree.NotBetweenExpr{E: sqlDollar[1].union.exprStatement(), From: sqlDollar[4].union.exprStatement(), To: sqlDollar[6].union.exprStatement()}
		}
	case 82:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:551
		{
			sqlVAL.union.val = sqlDollar[2].union.subqueryStatement()
			sqlVAL.union.val.(*tree.Subquery).Exists = true
		}
	case 83:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:556
		{
			sqlVAL.union.val = sqlDollar[1].union.valueStatement()
		}
	case 84:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:557
		{
			sqlVAL.union.val = sqlDollar[1].union.valueStatement()
		}
	case 85:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:558
		{
			sqlVAL.union.val = sqlDollar[1].union.valueStatement()
		}
	case 86:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:559
		{
			sqlVAL.union.val = &tree.Value{&value.ConstTrue}
		}
	case 87:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:560
		{
			sqlVAL.union.val = &tree.Value{&value.ConstFalse}
		}
	case 88:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:561
		{
			sqlVAL.union.val = &tree.Value{&value.ConstNull}
		}
	case 89:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:563
		{
			sqlVAL.union.val = sqlDollar[1].union.valueStatement()
		}
	case 90:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:564
		{
			sqlVAL.union.val = sqlDollar[2].union.valueStatement()
		}
	case 91:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:565
		{
			sqlVAL.union.val = sqlDollar[2].union.setNegative()
		}
	case 92:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:570
		{
			sqlVAL.union.val = sqlDollar[1].union.funcStatement()
		}
	case 93:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:574
		{
			sqlVAL.union.val = sqlDollar[1].union.funcStatement()
		}
	case 94:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:579
		{
			sqlVAL.union.val = &tree.FuncExpr{Name: sqlDollar[1].str}
		}
	case 95:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:583
		{
			sqlVAL.union.val = &tree.FuncExpr{Name: sqlDollar[1].str, Es: sqlDollar[3].union.exprStatements()}
		}
	case 96:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:588
		{
			sqlVAL.union.val = &tree.FuncExpr{Name: "cast", Es: tree.ExprStatements{sqlDollar[3].union.exprStatement(), sqlDollar[5].union.exprStatement()}}
		}
	case 97:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:592
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 98:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:594
		{
			sqlVAL.union.val = &tree.Value{value.NewString("int")}
		}
	case 99:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:595
		{
			sqlVAL.union.val = &tree.Value{value.NewString("bool")}
		}
	case 100:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:596
		{
			sqlVAL.union.val = &tree.Value{value.NewString("time")}
		}
	case 101:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:597
		{
			sqlVAL.union.val = &tree.Value{value.NewString("float")}
		}
	case 102:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:598
		{
			sqlVAL.union.val = &tree.Value{value.NewString("string")}
		}
	case 103:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:603
		{
			sqlVAL.union.val = &tree.AliasClause{Alias: tree.Name(sqlDollar[2].str), Cols: sqlDollar[3].union.nameList()}
		}
	case 104:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:607
		{
			sqlVAL.union.val = &tree.AliasClause{Alias: tree.Name(sqlDollar[1].str), Cols: sqlDollar[2].union.nameList()}
		}
	case 105:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:611
		{
			sqlVAL.union.val = sqlDollar[1].union.aliasClause()
		}
	case 106:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:612
		{
			sqlVAL.union.val = nil
		}
	case 107:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:616
		{
			sqlVAL.union.val = &tree.Subquery{Select: sqlDollar[2].union.selectStatement(), Exists: false}
		}
	case 108:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:619
		{
			sqlVAL.union.val = sqlDollar[1].union.relationStatement()
		}
	case 109:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:624
		{
			sqlVAL.union.val = &tree.UnionClause{
				Type:  tree.UnionOp,
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
				All:   sqlDollar[3].union.bool(),
			}
		}
	case 110:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:633
		{
			sqlVAL.union.val = &tree.UnionClause{
				Type:  tree.IntersectOp,
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
				All:   sqlDollar[3].union.bool(),
			}
		}
	case 111:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:642
		{
			sqlVAL.union.val = &tree.UnionClause{
				Type:  tree.ExceptOp,
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
				All:   sqlDollar[3].union.bool(),
			}
		}
	case 112:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:651
		{
			sqlVAL.union.val = true
		}
	case 113:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:652
		{
			sqlVAL.union.val = false
		}
	case 114:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:653
		{
			sqlVAL.union.val = false
		}
	case 115:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:658
		{
			sqlVAL.union.val = &tree.JoinClause{
				Type:  tree.CrossOp,
				Cond:  &tree.NonJoinCond{},
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
			}
		}
	case 116:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:667
		{
			sqlVAL.union.val = &tree.JoinClause{
				Type:  sqlDollar[2].union.joinType(),
				Cond:  sqlDollar[5].union.joinCond(),
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
			}
		}
	case 117:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:676
		{
			sqlVAL.union.val = &tree.JoinClause{
				Type:  tree.InnerOp,
				Cond:  sqlDollar[4].union.joinCond(),
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[3].union.relationStatement(),
			}
		}
	case 118:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:685
		{
			sqlVAL.union.val = &tree.JoinClause{
				Type:  tree.NaturalOp,
				Cond:  &tree.NonJoinCond{},
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
			}
		}
	case 119:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:694
		{
			sqlVAL.union.val = &tree.OnJoinCond{E: sqlDollar[2].union.exprStatement()}
		}
	case 120:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:696
		{
			sqlVAL.union.val = tree.FullOp
		}
	case 121:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:697
		{
			sqlVAL.union.val = tree.LeftOp
		}
	case 122:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:698
		{
			sqlVAL.union.val = tree.RightOp
		}
	case 123:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:699
		{
			sqlVAL.union.val = tree.InnerOp
		}
	case 124:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:701
		{
		}
	case 125:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:702
		{
		}
	case 126:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:707
		{
			sqlVAL.union.val = &tree.AliasedTable{
				Tbl: sqlDollar[1].union.tableName(),
				As:  sqlDollar[2].union.aliasClause(),
			}
		}
	case 127:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:714
		{
			sqlVAL.union.val = &tree.AliasedTable{
				Tbl: &tree.Subquery{Select: sqlDollar[1].union.selectStatement()},
				As:  sqlDollar[2].union.aliasClause(),
			}
		}
	case 128:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:724
		{
			sqlVAL.union.val = &tree.TableName{NumParts: 1, Parts: [2]tree.Name{tree.Name(sqlDollar[1].str)}}
		}
	case 129:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:728
		{
			sqlVAL.union.val = &tree.TableName{NumParts: 2, Parts: [2]tree.Name{tree.Name(sqlDollar[1].str), tree.Name(sqlDollar[3].str)}}
		}
	case 130:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:735
		{
			sqlVAL.union.val = tree.ColunmNameList{tree.ColunmName{Path: tree.Name(sqlDollar[1].str)}}
		}
	case 131:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:739
		{
			sqlVAL.union.val = tree.ColunmNameList{tree.ColunmName{Path: tree.Name(sqlDollar[1].str), Index: sqlDollar[3].union.exprStatement()}}
		}
	case 132:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:743
		{
			sqlVAL.union.val = append(sqlDollar[1].union.colunmNameList(), tree.ColunmName{Path: tree.Name(sqlDollar[3].str)})
		}
	case 133:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:747
		{
			sqlVAL.union.val = append(sqlDollar[1].union.colunmNameList(), tree.ColunmName{Path: tree.Name(sqlDollar[3].str), Index: sqlDollar[5].union.exprStatement()})
		}
	case 134:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:752
		{
			sqlVAL.union.val = sqlDollar[2].union.nameList()
		}
	case 135:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:753
		{
			sqlVAL.union.val = tree.NameList(nil)
		}
	case 136:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:756
		{
			sqlVAL.union.val = tree.NameList{tree.Name(sqlDollar[1].str)}
		}
	case 137:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:760
		{
			sqlVAL.union.val = append(sqlDollar[1].union.nameList(), tree.Name(sqlDollar[3].str))
		}
	}
	goto sqlstack /* stack new state and value */
}
