// Code generated by goyacc -o sql.go -p sql -v sql.output sql.y. DO NOT EDIT.

//line sql.y:2

package parser

import __yyfmt__ "fmt"

//line sql.y:3

import (
	"github.com/deepfabric/thinkbase/pkg/sql/tree"
	"github.com/deepfabric/thinkbase/pkg/vm/value"
)

//line sql.y:13

type sqlSymUnion struct {
	val interface{}
}

func (u *sqlSymUnion) bool() bool {
	return u.val.(bool)
}

func (u *sqlSymUnion) isNull() bool {
	return u.val == nil
}

func (u *sqlSymUnion) setNegative() *tree.Value {
	v, ok := u.val.(*tree.Value)
	if !ok {
		return nil
	}
	i, ok := value.AsInt(v.E)
	if !ok {
		return nil
	}
	return &tree.Value{value.NewInt(int64(i) * -1)}
}

func (u *sqlSymUnion) valueStatement() *tree.Value {
	return u.val.(*tree.Value)
}

func (u *sqlSymUnion) selectStatement() *tree.Select {
	return u.val.(*tree.Select)
}

func (u *sqlSymUnion) limitStatement() *tree.Limit {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.Limit)
}

func (u *sqlSymUnion) orderByStatement() tree.OrderBy {
	if u.val == nil {
		return nil
	}
	return u.val.(tree.OrderBy)
}

func (u *sqlSymUnion) relationStatement() tree.RelationStatement {
	if u.val == nil {
		return nil
	}
	return u.val.(tree.RelationStatement)
}

func (u *sqlSymUnion) joinStatement() *tree.JoinClause {
	return u.val.(*tree.JoinClause)
}

func (u *sqlSymUnion) unionStatement() *tree.UnionClause {
	return u.val.(*tree.UnionClause)
}

func (u *sqlSymUnion) simpleSelectStatement() *tree.SelectClause {
	return u.val.(*tree.SelectClause)
}

func (u *sqlSymUnion) fromStatement() *tree.From {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.From)
}

func (u *sqlSymUnion) groupByStatement() *tree.GroupBy {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.GroupBy)
}

func (u *sqlSymUnion) whereStatement() *tree.Where {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.Where)
}

func (u *sqlSymUnion) subqueryStatement() *tree.Subquery {
	return u.val.(*tree.Subquery)
}

func (u *sqlSymUnion) funcStatement() *tree.FuncExpr {
	return u.val.(*tree.FuncExpr)
}

func (u *sqlSymUnion) selectExprs() tree.SelectExprs {
	return u.val.(tree.SelectExprs)
}

func (u *sqlSymUnion) selectExpr() *tree.SelectExpr {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.SelectExpr)
}

func (u *sqlSymUnion) tableStatements() tree.TableStatements {
	return u.val.(tree.TableStatements)
}

func (u *sqlSymUnion) tableStatement() tree.TableStatement {
	return u.val.(tree.TableStatement)
}

func (u *sqlSymUnion) limit() *tree.Limit {
	return u.val.(*tree.Limit)
}

func (u *sqlSymUnion) orderStatement() *tree.Order {
	return u.val.(*tree.Order)
}

func (u *sqlSymUnion) direction() tree.Direction {
	return u.val.(tree.Direction)
}

func (u *sqlSymUnion) joinType() tree.JoinType {
	return u.val.(tree.JoinType)
}

func (u *sqlSymUnion) joinCond() tree.JoinCond {
	return u.val.(tree.JoinCond)
}

func (u *sqlSymUnion) tableName() *tree.TableName {
	return u.val.(*tree.TableName)
}

func (u *sqlSymUnion) nameList() tree.NameList {
	return u.val.(tree.NameList)
}

func (u *sqlSymUnion) exprStatement() tree.ExprStatement {
	return u.val.(tree.ExprStatement)
}

func (u *sqlSymUnion) exprStatements() tree.ExprStatements {
	return u.val.(tree.ExprStatements)
}

func (u *sqlSymUnion) colunmNameList() tree.ColunmNameList {
	return u.val.(tree.ColunmNameList)
}

func (u *sqlSymUnion) aliasClause() *tree.AliasClause {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.AliasClause)
}

//line sql.y:226
type sqlSymType struct {
	yys   int
	id    int32
	pos   int32
	byt   byte
	str   string
	union sqlSymUnion
}

const IDENT = 57346
const ICONST = 57347
const FCONST = 57348
const SCONST = 57349
const LESS_EQUALS = 57350
const GREATER_EQUALS = 57351
const NOT_EQUALS = 57352
const ALL = 57353
const AND = 57354
const AS = 57355
const ASC = 57356
const BETWEEN = 57357
const BOOL = 57358
const BY = 57359
const CAST = 57360
const CROSS = 57361
const DESC = 57362
const DISTINCT = 57363
const EXCEPT = 57364
const EXISTS = 57365
const FALSE = 57366
const FETCH = 57367
const FIRST = 57368
const FLOAT = 57369
const FROM = 57370
const FULL = 57371
const GROUP = 57372
const HAVING = 57373
const INNER = 57374
const INT = 57375
const INTERSECT = 57376
const IS = 57377
const JOIN = 57378
const NATURAL = 57379
const NEXT = 57380
const NOT = 57381
const NULL = 57382
const OFFSET = 57383
const ON = 57384
const ONLY = 57385
const OR = 57386
const ORDER = 57387
const OUTER = 57388
const RIGHT = 57389
const ROW = 57390
const ROWS = 57391
const SELECT = 57392
const STRING = 57393
const TIME = 57394
const TRUE = 57395
const UNION = 57396
const WHERE = 57397
const NOT_LA = 57398
const AT = 57399
const UMINUS = 57400
const LEFT = 57401

var sqlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"ICONST",
	"FCONST",
	"SCONST",
	"LESS_EQUALS",
	"GREATER_EQUALS",
	"NOT_EQUALS",
	"ALL",
	"AND",
	"AS",
	"ASC",
	"BETWEEN",
	"BOOL",
	"BY",
	"CAST",
	"CROSS",
	"DESC",
	"DISTINCT",
	"EXCEPT",
	"EXISTS",
	"FALSE",
	"FETCH",
	"FIRST",
	"FLOAT",
	"FROM",
	"FULL",
	"GROUP",
	"HAVING",
	"INNER",
	"INT",
	"INTERSECT",
	"IS",
	"JOIN",
	"NATURAL",
	"NEXT",
	"NOT",
	"NULL",
	"OFFSET",
	"ON",
	"ONLY",
	"OR",
	"ORDER",
	"OUTER",
	"RIGHT",
	"ROW",
	"ROWS",
	"SELECT",
	"STRING",
	"TIME",
	"TRUE",
	"UNION",
	"WHERE",
	"NOT_LA",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'<'",
	"'>'",
	"'='",
	"'['",
	"']'",
	"'('",
	"')'",
	"'.'",
	"AT",
	"UMINUS",
	"LEFT",
	"','",
}
var sqlStatenames = [...]string{}

const sqlEofCode = 1
const sqlErrCode = 2
const sqlInitialStackSize = 16

//line sql.y:774

//line yacctab:1
var sqlExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 4,
	1, 5,
	25, 5,
	41, 5,
	68, 5,
	-2, 108,
	-1, 58,
	67, 138,
	-2, 129,
}

const sqlPrivate = 57344

const sqlLast = 415

var sqlAct = [...]int{

	44, 40, 175, 218, 5, 197, 150, 47, 10, 130,
	145, 185, 142, 84, 4, 3, 208, 10, 94, 209,
	200, 18, 90, 4, 208, 23, 38, 188, 192, 28,
	92, 24, 27, 193, 239, 207, 74, 73, 10, 32,
	120, 119, 35, 72, 26, 100, 30, 31, 115, 116,
	117, 136, 143, 67, 46, 63, 147, 34, 87, 118,
	58, 13, 14, 97, 25, 121, 22, 17, 66, 233,
	13, 127, 131, 186, 187, 91, 101, 102, 103, 104,
	105, 22, 33, 69, 10, 75, 98, 10, 10, 10,
	10, 13, 204, 10, 97, 96, 135, 151, 155, 156,
	10, 99, 159, 160, 161, 162, 163, 164, 165, 166,
	167, 168, 169, 170, 154, 132, 153, 98, 148, 234,
	122, 176, 177, 10, 128, 115, 96, 182, 97, 4,
	36, 172, 158, 157, 134, 22, 123, 13, 194, 97,
	13, 13, 13, 13, 85, 196, 13, 11, 14, 199,
	173, 98, 229, 13, 195, 125, 99, 103, 104, 105,
	96, 97, 98, 231, 203, 68, 82, 126, 93, 228,
	152, 96, 206, 201, 202, 81, 13, 98, 83, 183,
	184, 69, 217, 212, 98, 219, 28, 232, 230, 181,
	131, 211, 198, 178, 12, 68, 32, 220, 215, 35,
	70, 26, 224, 30, 31, 151, 223, 221, 10, 222,
	225, 9, 22, 22, 34, 171, 114, 14, 51, 52,
	53, 235, 176, 236, 137, 238, 237, 138, 139, 140,
	141, 62, 97, 144, 190, 97, 45, 55, 21, 33,
	191, 76, 86, 14, 51, 52, 53, 101, 102, 103,
	104, 105, 43, 56, 216, 98, 14, 62, 98, 71,
	39, 13, 45, 55, 96, 20, 54, 96, 79, 80,
	48, 49, 28, 77, 214, 27, 88, 89, 43, 56,
	57, 174, 32, 78, 213, 35, 14, 26, 50, 30,
	31, 60, 54, 59, 180, 226, 48, 49, 41, 227,
	34, 14, 51, 52, 53, 19, 57, 25, 14, 51,
	52, 53, 42, 28, 146, 62, 124, 97, 210, 179,
	45, 55, 62, 32, 29, 33, 35, 45, 55, 205,
	30, 31, 14, 51, 52, 53, 43, 56, 64, 14,
	98, 34, 65, 43, 56, 149, 62, 97, 95, 96,
	54, 133, 55, 129, 48, 49, 41, 54, 109, 110,
	111, 48, 49, 15, 57, 112, 33, 16, 56, 37,
	98, 57, 61, 189, 101, 102, 103, 104, 105, 96,
	8, 54, 7, 6, 2, 48, 49, 1, 0, 0,
	0, 0, 0, 0, 0, 57, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 113, 101, 102, 103,
	104, 105, 106, 107, 108,
}
var sqlPact = [...]int{

	144, -1000, -1000, -1000, 22, 252, -1000, -1000, -1000, 144,
	-38, 253, 239, -10, -1000, 140, -1000, 183, -1000, -1000,
	282, -30, -1000, -32, 282, 262, 262, 262, 139, 130,
	144, 108, 12, 12, 12, -1000, 2, 297, -1000, -1000,
	335, -1000, -1000, 304, 350, -19, -1000, -38, 328, 328,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 304, -10, -1000,
	-1000, -26, -27, 304, -1000, -1000, 42, 170, 129, 304,
	304, -30, -1000, 282, 252, -14, 144, -1000, -1000, 144,
	144, 144, 144, 10, -1000, 144, -1000, -1000, -1000, -1000,
	1, 297, 58, 2, -1000, 282, 304, 304, 93, -1000,
	142, 328, 328, 328, 328, 328, 328, 328, 328, 328,
	328, 328, 328, 200, -1000, 144, 98, 98, 82, 213,
	304, 127, -1000, -1000, 122, -1000, -1000, 223, 25, -46,
	-1000, 220, -1000, -40, -1000, -1000, 304, 167, 294, 167,
	-1000, 10, -1000, 304, -1000, 162, -1000, 304, -1000, -53,
	-1000, 252, 252, 1, -1000, 149, 142, -1000, 52, 98,
	98, -1000, -1000, -1000, 19, 19, 19, 19, 19, 19,
	317, 328, -33, -1000, -1000, -49, 223, 305, -1000, 25,
	-1000, 304, -1000, 279, 269, -1000, -1000, -1000, 304, -1000,
	-1000, -1000, -1000, 282, 116, -1000, 223, 154, 180, 223,
	58, -1000, -1000, 162, -1000, 328, 190, -1000, 304, -1000,
	136, 26, 51, -1000, -1000, -1000, -1000, -1000, -1000, 304,
	304, -1000, 154, 19, 328, 223, -34, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 223, -57, -1000, 19, -1000,
}
var sqlPgo = [...]int{

	0, 387, 384, 15, 13, 383, 382, 147, 380, 170,
	373, 60, 372, 238, 18, 4, 7, 369, 43, 367,
	363, 353, 351, 22, 345, 2, 130, 5, 342, 338,
	241, 242, 12, 324, 68, 53, 319, 11, 316, 314,
	10, 1, 0, 312, 54, 3, 305, 21, 9, 6,
	26, 299, 295, 294, 293, 291, 288,
}
var sqlR1 = [...]int{

	0, 1, 2, 3, 20, 20, 19, 21, 21, 48,
	10, 10, 10, 29, 29, 28, 28, 28, 28, 34,
	35, 35, 36, 36, 36, 37, 37, 38, 38, 4,
	4, 4, 4, 4, 8, 8, 17, 26, 26, 50,
	50, 50, 50, 23, 23, 24, 24, 40, 40, 39,
	27, 27, 45, 45, 25, 25, 41, 41, 41, 41,
	41, 41, 41, 42, 42, 42, 42, 42, 42, 42,
	42, 42, 42, 43, 43, 43, 43, 43, 43, 43,
	43, 43, 44, 44, 44, 44, 44, 44, 44, 53,
	53, 53, 56, 56, 54, 54, 55, 52, 51, 51,
	51, 51, 51, 46, 46, 47, 47, 9, 7, 6,
	6, 6, 30, 30, 30, 5, 5, 5, 5, 32,
	33, 33, 33, 33, 31, 31, 49, 49, 15, 16,
	16, 16, 16, 18, 18, 22, 22, 11, 12, 14,
	13,
}
var sqlR2 = [...]int{

	0, 1, 1, 3, 1, 0, 3, 1, 3, 2,
	1, 1, 0, 1, 0, 2, 2, 1, 1, 5,
	2, 3, 1, 3, 0, 1, 1, 1, 1, 2,
	1, 1, 1, 4, 6, 7, 1, 1, 3, 1,
	2, 3, 1, 2, 0, 1, 3, 1, 0, 2,
	3, 0, 2, 0, 1, 3, 1, 2, 3, 3,
	3, 4, 1, 1, 1, 2, 2, 3, 3, 3,
	3, 3, 1, 3, 3, 3, 3, 3, 3, 5,
	6, 2, 1, 1, 1, 1, 1, 1, 3, 1,
	2, 2, 1, 1, 3, 4, 6, 1, 1, 1,
	1, 1, 1, 3, 2, 1, 0, 3, 1, 4,
	4, 4, 1, 1, 0, 4, 5, 4, 4, 2,
	2, 2, 2, 1, 1, 0, 2, 2, 1, 1,
	4, 3, 6, 3, 0, 1, 3, 1, 1, 1,
	1,
}
var sqlChk = [...]int{

	-1000, -1, -2, -3, -4, -15, -5, -6, -8, 67,
	-16, -7, 50, -11, 4, -20, -19, 45, -47, -46,
	13, -13, -11, -3, 69, 54, 34, 22, 19, -33,
	36, 37, 29, 72, 47, 32, -26, -17, -50, 21,
	-41, 59, -43, 39, -42, 23, -44, -16, 57, 58,
	-56, 5, 6, 7, 53, 24, 40, 67, -11, -54,
	-55, -12, 18, 65, -29, -28, -34, -35, 25, 41,
	17, -13, -18, 67, 68, -11, -30, 11, 21, -30,
	-30, 36, 36, -7, -4, 36, -31, 46, -31, -31,
	-23, 73, 28, -26, -14, 13, 44, 12, 35, -11,
	-41, 57, 58, 59, 60, 61, 62, 63, 64, 8,
	9, 10, 15, 56, -9, 67, -42, -42, -41, 67,
	67, -41, -35, -34, -38, 26, 38, -41, -44, -21,
	-48, -41, -18, -22, -11, -47, 65, -7, -7, -7,
	-7, -7, -32, 42, -7, -40, -39, 55, -50, -24,
	-49, -15, -9, -23, -14, -41, -41, 40, 39, -42,
	-42, -42, -42, -42, -42, -42, -42, -42, -42, -42,
	-42, 15, -3, 68, 68, -25, -41, -41, 66, -36,
	-53, 67, 5, 57, 58, -37, 48, 49, 73, -10,
	14, 20, 68, 73, -41, -32, -41, -27, 30, -41,
	73, -47, -47, -40, 40, 12, -42, 68, 73, 68,
	13, -37, -41, 5, 5, -48, -11, 66, -45, 31,
	17, -49, -27, -42, 12, -41, -52, -51, 33, 16,
	52, 27, 51, 43, 68, -41, -25, -45, -42, 68,
}
var sqlDef = [...]int{

	0, -2, 1, 2, -2, 106, 30, 31, 32, 0,
	128, 0, 0, 129, 137, 14, 4, 0, 29, 105,
	0, 134, 140, 0, 0, 114, 114, 114, 0, 0,
	0, 0, 125, 125, 125, 123, 44, 0, 37, 36,
	39, 42, 56, 0, 62, 0, 63, 64, 0, 0,
	72, 82, 83, 84, 85, 86, 87, 0, -2, 92,
	93, 0, 0, 0, 3, 13, 17, 18, 0, 0,
	0, 134, 104, 0, 106, 131, 0, 112, 113, 0,
	0, 0, 0, 0, 108, 0, 120, 124, 121, 122,
	48, 0, 0, 44, 40, 0, 0, 0, 0, 139,
	57, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 81, 0, 65, 66, 0, 0,
	0, 0, 15, 16, 24, 27, 28, 20, 63, 6,
	7, 12, 103, 0, 135, 33, 0, 109, 110, 111,
	115, 0, 117, 0, 118, 51, 47, 0, 38, 43,
	45, 106, 106, 48, 41, 58, 59, 60, 0, 67,
	68, 69, 70, 71, 73, 74, 75, 76, 77, 78,
	0, 0, 0, 88, 94, 0, 54, 0, 130, 0,
	22, 0, 89, 0, 0, 21, 25, 26, 0, 9,
	10, 11, 133, 0, 0, 116, 119, 53, 0, 49,
	0, 126, 127, 51, 61, 0, 0, 107, 0, 95,
	0, 0, 0, 90, 91, 8, 136, 132, 34, 0,
	0, 46, 53, 79, 0, 55, 0, 97, 98, 99,
	100, 101, 102, 19, 23, 52, 50, 35, 80, 96,
}
var sqlTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 61, 3, 3,
	67, 68, 59, 57, 73, 58, 69, 60, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	62, 64, 63, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 65, 3, 66,
}
var sqlTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 70, 71, 72,
}
var sqlTok3 = [...]int{
	0,
}

var sqlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	sqlDebug        = 0
	sqlErrorVerbose = false
)

type sqlLexer interface {
	Lex(lval *sqlSymType) int
	Error(s string)
}

type sqlParser interface {
	Parse(sqlLexer) int
	Lookahead() int
}

type sqlParserImpl struct {
	lval  sqlSymType
	stack [sqlInitialStackSize]sqlSymType
	char  int
}

func (p *sqlParserImpl) Lookahead() int {
	return p.char
}

func sqlNewParser() sqlParser {
	return &sqlParserImpl{}
}

const sqlFlag = -1000

func sqlTokname(c int) string {
	if c >= 1 && c-1 < len(sqlToknames) {
		if sqlToknames[c-1] != "" {
			return sqlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func sqlStatname(s int) string {
	if s >= 0 && s < len(sqlStatenames) {
		if sqlStatenames[s] != "" {
			return sqlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func sqlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !sqlErrorVerbose {
		return "syntax error"
	}

	for _, e := range sqlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + sqlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := sqlPact[state]
	for tok := TOKSTART; tok-1 < len(sqlToknames); tok++ {
		if n := base + tok; n >= 0 && n < sqlLast && sqlChk[sqlAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if sqlDef[state] == -2 {
		i := 0
		for sqlExca[i] != -1 || sqlExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; sqlExca[i] >= 0; i += 2 {
			tok := sqlExca[i]
			if tok < TOKSTART || sqlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if sqlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += sqlTokname(tok)
	}
	return res
}

func sqllex1(lex sqlLexer, lval *sqlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = sqlTok1[0]
		goto out
	}
	if char < len(sqlTok1) {
		token = sqlTok1[char]
		goto out
	}
	if char >= sqlPrivate {
		if char < sqlPrivate+len(sqlTok2) {
			token = sqlTok2[char-sqlPrivate]
			goto out
		}
	}
	for i := 0; i < len(sqlTok3); i += 2 {
		token = sqlTok3[i+0]
		if token == char {
			token = sqlTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = sqlTok2[1] /* unknown char */
	}
	if sqlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", sqlTokname(token), uint(char))
	}
	return char, token
}

func sqlParse(sqllex sqlLexer) int {
	return sqlNewParser().Parse(sqllex)
}

func (sqlrcvr *sqlParserImpl) Parse(sqllex sqlLexer) int {
	var sqln int
	var sqlVAL sqlSymType
	var sqlDollar []sqlSymType
	_ = sqlDollar // silence set and not used
	sqlS := sqlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	sqlstate := 0
	sqlrcvr.char = -1
	sqltoken := -1 // sqlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		sqlstate = -1
		sqlrcvr.char = -1
		sqltoken = -1
	}()
	sqlp := -1
	goto sqlstack

ret0:
	return 0

ret1:
	return 1

sqlstack:
	/* put a state and value onto the stack */
	if sqlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", sqlTokname(sqltoken), sqlStatname(sqlstate))
	}

	sqlp++
	if sqlp >= len(sqlS) {
		nyys := make([]sqlSymType, len(sqlS)*2)
		copy(nyys, sqlS)
		sqlS = nyys
	}
	sqlS[sqlp] = sqlVAL
	sqlS[sqlp].yys = sqlstate

sqlnewstate:
	sqln = sqlPact[sqlstate]
	if sqln <= sqlFlag {
		goto sqldefault /* simple state */
	}
	if sqlrcvr.char < 0 {
		sqlrcvr.char, sqltoken = sqllex1(sqllex, &sqlrcvr.lval)
	}
	sqln += sqltoken
	if sqln < 0 || sqln >= sqlLast {
		goto sqldefault
	}
	sqln = sqlAct[sqln]
	if sqlChk[sqln] == sqltoken { /* valid shift */
		sqlrcvr.char = -1
		sqltoken = -1
		sqlVAL = sqlrcvr.lval
		sqlstate = sqln
		if Errflag > 0 {
			Errflag--
		}
		goto sqlstack
	}

sqldefault:
	/* default state action */
	sqln = sqlDef[sqlstate]
	if sqln == -2 {
		if sqlrcvr.char < 0 {
			sqlrcvr.char, sqltoken = sqllex1(sqllex, &sqlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if sqlExca[xi+0] == -1 && sqlExca[xi+1] == sqlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			sqln = sqlExca[xi+0]
			if sqln < 0 || sqln == sqltoken {
				break
			}
		}
		sqln = sqlExca[xi+1]
		if sqln < 0 {
			goto ret0
		}
	}
	if sqln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			sqllex.Error(sqlErrorMessage(sqlstate, sqltoken))
			Nerrs++
			if sqlDebug >= 1 {
				__yyfmt__.Printf("%s", sqlStatname(sqlstate))
				__yyfmt__.Printf(" saw %s\n", sqlTokname(sqltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for sqlp >= 0 {
				sqln = sqlPact[sqlS[sqlp].yys] + sqlErrCode
				if sqln >= 0 && sqln < sqlLast {
					sqlstate = sqlAct[sqln] /* simulate a shift of "error" */
					if sqlChk[sqlstate] == sqlErrCode {
						goto sqlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if sqlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", sqlS[sqlp].yys)
				}
				sqlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if sqlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", sqlTokname(sqltoken))
			}
			if sqltoken == sqlEofCode {
				goto ret1
			}
			sqlrcvr.char = -1
			sqltoken = -1
			goto sqlnewstate /* try again in the same state */
		}
	}

	/* reduction by production sqln */
	if sqlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", sqln, sqlStatname(sqlstate))
	}

	sqlnt := sqln
	sqlpt := sqlp
	_ = sqlpt // guard against "declared and not used"

	sqlp -= sqlR2[sqln]
	// sqlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if sqlp+1 >= len(sqlS) {
		nyys := make([]sqlSymType, len(sqlS)*2)
		copy(nyys, sqlS)
		sqlS = nyys
	}
	sqlVAL = sqlS[sqlp+1]

	/* consult goto table to find next state */
	sqln = sqlR1[sqln]
	sqlg := sqlPgo[sqln]
	sqlj := sqlg + sqlS[sqlp].yys + 1

	if sqlj >= sqlLast {
		sqlstate = sqlAct[sqlg]
	} else {
		sqlstate = sqlAct[sqlj]
		if sqlChk[sqlstate] != -sqln {
			sqlstate = sqlAct[sqlg]
		}
	}
	// dummy call; replaced with literal code
	switch sqlnt {

	case 1:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:320
		{
			sqllex.(*lexer).SetStmt(sqlDollar[1].union.selectStatement())
		}
	case 2:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:322
		{
			sqlVAL.union.val = sqlDollar[1].union.selectStatement()
		}
	case 3:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:325
		{
			sqlVAL.union.val = &tree.Select{
				Limit:    sqlDollar[3].union.limitStatement(),
				OrderBy:  sqlDollar[2].union.orderByStatement(),
				Relation: sqlDollar[1].union.relationStatement(),
			}
		}
	case 4:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:335
		{
			sqlVAL.union.val = sqlDollar[1].union.orderByStatement()
		}
	case 5:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:336
		{
			sqlVAL.union.val = nil
		}
	case 6:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:338
		{
			sqlVAL.union.val = sqlDollar[3].union.orderByStatement()
		}
	case 7:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:340
		{
			sqlVAL.union.val = tree.OrderBy{sqlDollar[1].union.orderStatement()}
		}
	case 8:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:341
		{
			sqlVAL.union.val = append(sqlDollar[1].union.orderByStatement(), sqlDollar[3].union.orderStatement())
		}
	case 9:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:344
		{
			sqlVAL.union.val = &tree.Order{
				E:    sqlDollar[1].union.exprStatement(),
				Type: sqlDollar[2].union.direction(),
			}
		}
	case 10:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:351
		{
			sqlVAL.union.val = tree.Ascending
		}
	case 11:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:352
		{
			sqlVAL.union.val = tree.Descending
		}
	case 12:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:353
		{
			sqlVAL.union.val = tree.DefaultDirection
		}
	case 13:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:356
		{
			sqlVAL.union.val = sqlDollar[1].union.limitStatement()
		}
	case 14:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:357
		{
			sqlVAL.union.val = nil
		}
	case 15:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:360
		{
			if sqlDollar[1].union.limitStatement() == nil {
				sqlVAL.union.val = sqlDollar[2].union.limitStatement()
			} else {
				sqlVAL.union.val = sqlDollar[1].union.limitStatement()
				sqlVAL.union.val.(*tree.Limit).Offset = sqlDollar[2].union.limitStatement().Offset
			}
		}
	case 16:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:369
		{
			sqlVAL.union.val = sqlDollar[1].union.limitStatement()
			if sqlDollar[2].union.limitStatement() != nil {
				sqlVAL.union.val.(*tree.Limit).Count = sqlDollar[2].union.limitStatement().Count
			}
		}
	case 17:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:376
		{
			sqlVAL.union.val = sqlDollar[1].union.limitStatement()
		}
	case 18:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:380
		{
			sqlVAL.union.val = sqlDollar[1].union.limitStatement()
		}
	case 19:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:385
		{
			sqlVAL.union.val = &tree.Limit{Count: sqlDollar[3].union.exprStatement()}
		}
	case 20:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:389
		{
			sqlVAL.union.val = &tree.Limit{Offset: sqlDollar[2].union.exprStatement()}
		}
	case 21:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:390
		{
			sqlVAL.union.val = &tree.Limit{Offset: sqlDollar[2].union.exprStatement()}
		}
	case 22:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:392
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 23:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:393
		{
			sqlVAL.union.val = sqlDollar[2].union.exprStatement()
		}
	case 24:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:394
		{
			sqlVAL.union.val = &tree.Value{value.NewInt(1)}
		}
	case 25:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:396
		{
		}
	case 26:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:397
		{
		}
	case 27:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:399
		{
		}
	case 28:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:400
		{
		}
	case 29:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:404
		{
			sqlVAL.union.val = &tree.AliasedTable{
				As:  sqlDollar[2].union.aliasClause(),
				Tbl: sqlDollar[1].union.tableName(),
			}
		}
	case 30:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:409
		{
			sqlVAL.union.val = sqlDollar[1].union.joinStatement()
		}
	case 31:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:410
		{
			sqlVAL.union.val = sqlDollar[1].union.unionStatement()
		}
	case 32:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:411
		{
			sqlVAL.union.val = sqlDollar[1].union.simpleSelectStatement()
		}
	case 33:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:412
		{
			sqlVAL.union.val = &tree.AliasedSelect{
				As:  sqlDollar[4].union.aliasClause(),
				Sel: sqlDollar[2].union.selectStatement(),
			}
		}
	case 34:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:420
		{
			sqlVAL.union.val = &tree.SelectClause{
				Distinct: false,
				Sel:      sqlDollar[2].union.selectExprs(),
				From:     sqlDollar[3].union.fromStatement(),
				Where:    sqlDollar[4].union.whereStatement(),
				Having:   sqlDollar[6].union.whereStatement(),
				GroupBy:  sqlDollar[5].union.groupByStatement(),
			}
		}
	case 35:
		sqlDollar = sqlS[sqlpt-7 : sqlpt+1]
//line sql.y:431
		{
			sqlVAL.union.val = &tree.SelectClause{
				Distinct: sqlDollar[2].union.bool(),
				Sel:      sqlDollar[3].union.selectExprs(),
				From:     sqlDollar[4].union.fromStatement(),
				Where:    sqlDollar[5].union.whereStatement(),
				Having:   sqlDollar[7].union.whereStatement(),
				GroupBy:  sqlDollar[6].union.groupByStatement(),
			}
		}
	case 36:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:444
		{
			sqlVAL.union.val = true
		}
	case 37:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:449
		{
			if sqlDollar[1].union.isNull() {
				sqlVAL.union.val = tree.SelectExprs{}
			} else {
				sqlVAL.union.val = tree.SelectExprs{sqlDollar[1].union.selectExpr()}
			}
		}
	case 38:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:457
		{
			if sqlDollar[3].union.isNull() {
				sqlVAL.union.val = sqlDollar[1].union.selectExprs()
			} else {
				sqlVAL.union.val = append(sqlDollar[1].union.selectExprs(), sqlDollar[3].union.selectExpr())
			}
		}
	case 39:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:466
		{
			sqlVAL.union.val = &tree.SelectExpr{E: sqlDollar[1].union.exprStatement()}
		}
	case 40:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:470
		{
			sqlVAL.union.val = &tree.SelectExpr{E: sqlDollar[1].union.exprStatement(), As: tree.Name(sqlDollar[2].str)}
		}
	case 41:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:474
		{
			sqlVAL.union.val = &tree.SelectExpr{E: sqlDollar[1].union.exprStatement(), As: tree.Name(sqlDollar[3].str)}
		}
	case 42:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:478
		{
			sqlVAL.union.val = nil
		}
	case 43:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:485
		{
			sqlVAL.union.val = &tree.From{sqlDollar[2].union.tableStatements()}
		}
	case 44:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:488
		{
			sqlVAL.union.val = nil
		}
	case 45:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:491
		{
			sqlVAL.union.val = tree.TableStatements{sqlDollar[1].union.tableStatement()}
		}
	case 46:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:495
		{
			sqlVAL.union.val = append(sqlDollar[1].union.tableStatements(), sqlDollar[3].union.tableStatement())
		}
	case 47:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:502
		{
			sqlVAL.union.val = &tree.Where{Type: tree.AstWhere, E: sqlDollar[1].union.exprStatement()}
		}
	case 48:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:505
		{
			sqlVAL.union.val = nil
		}
	case 49:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:507
		{
			sqlVAL.union.val = sqlDollar[2].union.exprStatement()
		}
	case 50:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:511
		{
			sqlVAL.union.val = &tree.GroupBy{sqlDollar[3].union.exprStatements()}
		}
	case 51:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:512
		{
			sqlVAL.union.val = nil
		}
	case 52:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:517
		{
			sqlVAL.union.val = &tree.Where{Type: tree.AstHaving, E: sqlDollar[2].union.exprStatement()}
		}
	case 53:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:520
		{
			sqlVAL.union.val = nil
		}
	case 54:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:524
		{
			sqlVAL.union.val = tree.ExprStatements{sqlDollar[1].union.exprStatement()}
		}
	case 55:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:525
		{
			sqlVAL.union.val = append(sqlDollar[1].union.exprStatements(), sqlDollar[3].union.exprStatement())
		}
	case 56:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:527
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 57:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:528
		{
			sqlVAL.union.val = &tree.NotExpr{E: sqlDollar[2].union.exprStatement()}
		}
	case 58:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:529
		{
			sqlVAL.union.val = &tree.OrExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 59:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:530
		{
			sqlVAL.union.val = &tree.AndExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 60:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:531
		{
			sqlVAL.union.val = &tree.IsNullExpr{E: sqlDollar[1].union.exprStatement()}
		}
	case 61:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:532
		{
			sqlVAL.union.val = &tree.IsNotNullExpr{E: sqlDollar[1].union.exprStatement()}
		}
	case 62:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:533
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 63:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:535
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 64:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:536
		{
			sqlVAL.union.val = sqlDollar[1].union.colunmNameList()
		}
	case 65:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:537
		{
			sqlVAL.union.val = sqlDollar[2].union.exprStatement()
		}
	case 66:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:538
		{
			sqlVAL.union.val = &tree.UnaryMinusExpr{E: sqlDollar[2].union.exprStatement()}
		}
	case 67:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:539
		{
			sqlVAL.union.val = &tree.PlusExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 68:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:540
		{
			sqlVAL.union.val = &tree.MinusExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 69:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:541
		{
			sqlVAL.union.val = &tree.MultExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 70:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:542
		{
			sqlVAL.union.val = &tree.DivExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 71:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:543
		{
			sqlVAL.union.val = &tree.ModExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 72:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:544
		{
			sqlVAL.union.val = sqlDollar[1].union.funcStatement()
		}
	case 73:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:546
		{
			sqlVAL.union.val = &tree.LtExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 74:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:547
		{
			sqlVAL.union.val = &tree.GtExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 75:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:548
		{
			sqlVAL.union.val = &tree.EqExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 76:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:549
		{
			sqlVAL.union.val = &tree.LeExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 77:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:550
		{
			sqlVAL.union.val = &tree.GeExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 78:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:551
		{
			sqlVAL.union.val = &tree.NeExpr{Left: sqlDollar[1].union.exprStatement(), Right: sqlDollar[3].union.exprStatement()}
		}
	case 79:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:552
		{
			sqlVAL.union.val = &tree.BetweenExpr{E: sqlDollar[1].union.exprStatement(), From: sqlDollar[3].union.exprStatement(), To: sqlDollar[5].union.exprStatement()}
		}
	case 80:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:553
		{
			sqlVAL.union.val = &tree.NotBetweenExpr{E: sqlDollar[1].union.exprStatement(), From: sqlDollar[4].union.exprStatement(), To: sqlDollar[6].union.exprStatement()}
		}
	case 81:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:554
		{
			sqlVAL.union.val = sqlDollar[2].union.subqueryStatement()
			sqlVAL.union.val.(*tree.Subquery).Exists = true
		}
	case 82:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:559
		{
			sqlVAL.union.val = sqlDollar[1].union.valueStatement()
		}
	case 83:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:560
		{
			sqlVAL.union.val = sqlDollar[1].union.valueStatement()
		}
	case 84:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:561
		{
			sqlVAL.union.val = sqlDollar[1].union.valueStatement()
		}
	case 85:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:562
		{
			sqlVAL.union.val = &tree.Value{&value.ConstTrue}
		}
	case 86:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:563
		{
			sqlVAL.union.val = &tree.Value{&value.ConstFalse}
		}
	case 87:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:564
		{
			sqlVAL.union.val = &tree.Value{&value.ConstNull}
		}
	case 88:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:565
		{
			sqlVAL.union.val = sqlDollar[2].union.exprStatement()
		}
	case 89:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:567
		{
			sqlVAL.union.val = sqlDollar[1].union.valueStatement()
		}
	case 90:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:568
		{
			sqlVAL.union.val = sqlDollar[2].union.valueStatement()
		}
	case 91:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:569
		{
			sqlVAL.union.val = sqlDollar[2].union.setNegative()
		}
	case 92:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:574
		{
			sqlVAL.union.val = sqlDollar[1].union.funcStatement()
		}
	case 93:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:578
		{
			sqlVAL.union.val = sqlDollar[1].union.funcStatement()
		}
	case 94:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:583
		{
			sqlVAL.union.val = &tree.FuncExpr{Name: sqlDollar[1].str}
		}
	case 95:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:587
		{
			sqlVAL.union.val = &tree.FuncExpr{Name: sqlDollar[1].str, Es: sqlDollar[3].union.exprStatements()}
		}
	case 96:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:592
		{
			sqlVAL.union.val = &tree.FuncExpr{Name: "cast", Es: tree.ExprStatements{sqlDollar[3].union.exprStatement(), sqlDollar[5].union.exprStatement()}}
		}
	case 97:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:596
		{
			sqlVAL.union.val = sqlDollar[1].union.exprStatement()
		}
	case 98:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:598
		{
			sqlVAL.union.val = &tree.Value{value.NewString("int")}
		}
	case 99:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:599
		{
			sqlVAL.union.val = &tree.Value{value.NewString("bool")}
		}
	case 100:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:600
		{
			sqlVAL.union.val = &tree.Value{value.NewString("time")}
		}
	case 101:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:601
		{
			sqlVAL.union.val = &tree.Value{value.NewString("float")}
		}
	case 102:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:602
		{
			sqlVAL.union.val = &tree.Value{value.NewString("string")}
		}
	case 103:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:607
		{
			sqlVAL.union.val = &tree.AliasClause{Alias: tree.Name(sqlDollar[2].str), Cols: sqlDollar[3].union.nameList()}
		}
	case 104:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:611
		{
			sqlVAL.union.val = &tree.AliasClause{Alias: tree.Name(sqlDollar[1].str), Cols: sqlDollar[2].union.nameList()}
		}
	case 105:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:615
		{
			sqlVAL.union.val = sqlDollar[1].union.aliasClause()
		}
	case 106:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:616
		{
			sqlVAL.union.val = nil
		}
	case 107:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:620
		{
			sqlVAL.union.val = &tree.Subquery{Select: sqlDollar[2].union.selectStatement(), Exists: false}
		}
	case 108:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:623
		{
			sqlVAL.union.val = sqlDollar[1].union.relationStatement()
		}
	case 109:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:628
		{
			sqlVAL.union.val = &tree.UnionClause{
				Type:  tree.UnionOp,
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
				All:   sqlDollar[3].union.bool(),
			}
		}
	case 110:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:637
		{
			sqlVAL.union.val = &tree.UnionClause{
				Type:  tree.IntersectOp,
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
				All:   sqlDollar[3].union.bool(),
			}
		}
	case 111:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:646
		{
			sqlVAL.union.val = &tree.UnionClause{
				Type:  tree.ExceptOp,
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
				All:   sqlDollar[3].union.bool(),
			}
		}
	case 112:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:655
		{
			sqlVAL.union.val = true
		}
	case 113:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:656
		{
			sqlVAL.union.val = false
		}
	case 114:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:657
		{
			sqlVAL.union.val = false
		}
	case 115:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:662
		{
			sqlVAL.union.val = &tree.JoinClause{
				Type:  tree.CrossOp,
				Cond:  &tree.NonJoinCond{},
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
			}
		}
	case 116:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:671
		{
			sqlVAL.union.val = &tree.JoinClause{
				Type:  sqlDollar[2].union.joinType(),
				Cond:  sqlDollar[5].union.joinCond(),
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
			}
		}
	case 117:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:680
		{
			sqlVAL.union.val = &tree.JoinClause{
				Type:  tree.InnerOp,
				Cond:  sqlDollar[4].union.joinCond(),
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[3].union.relationStatement(),
			}
		}
	case 118:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:689
		{
			sqlVAL.union.val = &tree.JoinClause{
				Type:  tree.NaturalOp,
				Cond:  &tree.NonJoinCond{},
				Left:  sqlDollar[1].union.relationStatement(),
				Right: sqlDollar[4].union.relationStatement(),
			}
		}
	case 119:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:698
		{
			sqlVAL.union.val = &tree.OnJoinCond{E: sqlDollar[2].union.exprStatement()}
		}
	case 120:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:700
		{
			sqlVAL.union.val = tree.FullOp
		}
	case 121:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:701
		{
			sqlVAL.union.val = tree.LeftOp
		}
	case 122:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:702
		{
			sqlVAL.union.val = tree.RightOp
		}
	case 123:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:703
		{
			sqlVAL.union.val = tree.InnerOp
		}
	case 124:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:705
		{
		}
	case 125:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:706
		{
		}
	case 126:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:711
		{
			sqlVAL.union.val = &tree.AliasedTable{
				Tbl: sqlDollar[1].union.tableName(),
				As:  sqlDollar[2].union.aliasClause(),
			}
		}
	case 127:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:718
		{
			sqlVAL.union.val = &tree.AliasedTable{
				Tbl: sqlDollar[1].union.subqueryStatement(),
				As:  sqlDollar[2].union.aliasClause(),
			}
		}
	case 128:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:728
		{
			sqlVAL.union.val = &tree.TableName{sqlDollar[1].union.colunmNameList()}
		}
	case 129:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:735
		{
			sqlVAL.union.val = tree.ColunmNameList{tree.ColunmName{Path: tree.Name(sqlDollar[1].str)}}
		}
	case 130:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:739
		{
			sqlVAL.union.val = tree.ColunmNameList{tree.ColunmName{Path: tree.Name(sqlDollar[1].str), Index: sqlDollar[3].union.exprStatement()}}
		}
	case 131:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:743
		{
			sqlVAL.union.val = append(sqlDollar[1].union.colunmNameList(), tree.ColunmName{Path: tree.Name(sqlDollar[3].str)})
		}
	case 132:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:747
		{
			sqlVAL.union.val = append(sqlDollar[1].union.colunmNameList(), tree.ColunmName{Path: tree.Name(sqlDollar[3].str), Index: sqlDollar[5].union.exprStatement()})
		}
	case 133:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:752
		{
			sqlVAL.union.val = sqlDollar[2].union.nameList()
		}
	case 134:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:753
		{
			sqlVAL.union.val = tree.NameList(nil)
		}
	case 135:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:756
		{
			sqlVAL.union.val = tree.NameList{tree.Name(sqlDollar[1].str)}
		}
	case 136:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:760
		{
			sqlVAL.union.val = append(sqlDollar[1].union.nameList(), tree.Name(sqlDollar[3].str))
		}
	}
	goto sqlstack /* stack new state and value */
}
